#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HubSpotr.Android.Resource", IsApplication=true)]

namespace HubSpotr.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			HubSpotr.Android.Core.Resource.Drawable.monoandroidsplash = HubSpotr.Android.Resource.Drawable.monoandroidsplash;
			HubSpotr.Android.Core.Resource.String.ApplicationName = HubSpotr.Android.Resource.String.ApplicationName;
			HubSpotr.Android.Core.Resource.String.Hello = HubSpotr.Android.Resource.String.Hello;
			HubSpotr.Android.Core.Resource.Style.Mono_Android_Theme_Splash = HubSpotr.Android.Resource.Style.Mono_Android_Theme_Splash;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int buttonBarButtonStyle = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int buttonBarStyle = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int black_overlay = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bubspot_04 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int hubspot_splash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_launcher = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_train = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int monoandroidsplash = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070010
			public const int button_LoginFace = 2131165200;
			
			// aapt resource value: 0x7f070004
			public const int discoveryProgress = 2131165188;
			
			// aapt resource value: 0x7f07000c
			public const int fullscreen_content_controls = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int hubItemName = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int hubItemParticipants = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int hubNameView = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int hubsView = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int imageView = 2131165197;
			
			// aapt resource value: 0x7f070002
			public const int postButton = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int postItemDate = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int postItemMessage = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int postItemOwner = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int postItemPicture = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int postText = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int postsView = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int progressBar = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int splashProgress = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Hub = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HubDiscovery = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HubItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PostItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Splash = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int Button_LoginFace = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int HL_HeaderTxt = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int HL_SubHeaderTXT = 2130968583;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int dummy_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int dummy_content = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int AppBaseTheme = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int AppTheme = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int ButtonBar = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int ButtonBarButton = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int FullscreenTheme = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ButtonBarContainerTheme = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int ButtonBarContainerTheme_buttonBarButtonStyle = 1;
			
			// aapt resource value: 0
			public const int ButtonBarContainerTheme_buttonBarStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
